### ISSUE TITLE
[Feature Request] Ability to send avatar icon

### ISSUE THREAD

**Issue by danjames92** [radonthetyrant/rutorrent-discord#1]
Would be most appreciated if possible!

**Comment by radonthetyrant** [comment]
Think thats something only discord can do, check this:

![image](https://user-images.githubusercontent.com/4189978/35198883-b5b539dc-fef5-11e7-96af-2bda17cd33bf.png)

**Comment by danjames92** [comment]
given the fact sonarr / radarr can do it with their slack option... I think it should be possible.

![firefox_2018-01-21_21-13-30](https://user-images.githubusercontent.com/16107603/35199034-edebc2a4-feef-11e7-81c6-d2b69d243fc1.png)

**Comment by radonthetyrant** [comment]
ah interesting. I'll check it out!

**Comment by danjames92** [comment]
@radonthetyrant any progress?

**Comment by radonthetyrant** [comment]
Added in ce3b06e75f65dbcecc8753950c3f2972ef9055a3
Feel free to try it out

**Comment by radonthetyrant** [comment]
closed, embed feature follows in #3
