### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by pinkairfreshener** [radonthetyrant/rutorrent-discord#11]
I used the following commands:

git clone https://github.com/radonthetyrant/rutorrent-discord.git ~/rutorrent-discord-tmp

mv ~/rutorrent-discord-tmp/discordpush ~/www/username.server123.seedhost.eu/username/rutorrent/plugins/

rm -rf ~/rutorrent-discord-tmp

I can confirm that the discordpush folder is successfully placed inside the rutorrent/plugins folder. I have added my webhook url on rutorrent and the plugin is enabled. However, when I add or remove a torrent, there is no discord notification. 

My webhook itself is working as I tested it using a different website.

Any help?

Thanks

**Comment by DoAndroids** [comment]
Did we discuss this on Reddit? :)
I.e. was it the missing php-curl library?

**Comment by pinkairfreshener** [comment]
Yeah that’s exactly what the issue was, all working now :)
