### ISSUE TITLE
does this work without the webui being open?

### ISSUE THREAD

**Issue by Rhodesia** [radonthetyrant/rutorrent-discord#2]
Im too lazy to keep my webui open 24/7

**Comment by radonthetyrant** [comment]
yes, it pushes the hooks to rtorrent, which works independent on the webui. the webui only helps to activate/configure the plugin

**Comment by radonthetyrant** [comment]
As a sidenote, as I have just discovered, is that a command seems to be needed in the .rtorrent.rc file:

`# Start rutorrent plugins automatically
execute = {sh,-c,/usr/bin/php /path/to/rutorrent/php/initplugins.php %USERNAME% &}`
where %USERNAME% needs to be replaced with the correct webserver user. I'm not sure if rutorrent adds this automatically
