### ISSUE TITLE
[Feature Request] Send embeds

### ISSUE THREAD

**Issue by samwiseg00** [radonthetyrant/rutorrent-discord#3]
It would be nice if it sent it as an ~~attachment~~ embed and made each item a field. I think it would be easier to read especially if you get a few of them.

**Comment by radonthetyrant** [comment]
Are you talking about the avatar as an attachment?

**Comment by samwiseg00** [comment]
No I really meant to ask for embeds... 
https://discordapp.com/developers/docs/resources/channel#embed-object

https://camo.githubusercontent.com/c987c1a58e3c75f8c74bd3589e65e807322af820/687474703a2f2f692e696d6775722e636f6d2f47656d636f42572e706e67

**Comment by radonthetyrant** [comment]
hm, so you mean like a text-embed instead of a simple message?

**Comment by samwiseg00** [comment]
yep.. it would look much nicer and way easier to read.

**Comment by radonthetyrant** [comment]
that seems like a good idea, will definitely check it out. thanks for the suggestion!

**Comment by samwiseg00** [comment]
Np.. one idea I had as well is you can do different colors for the different type of messages...

**Comment by radonthetyrant** [comment]
the plugin has a config file for the messages, couldn't this be achieved through editing the string values?
https://github.com/radonthetyrant/rutorrent-discord/blob/master/discordpush/conf.php

**Comment by samwiseg00** [comment]
It Might I was going to try that but I was not sure if you had to specify that it was an embed. I am not familiar with php.. I can try editing it and sending the json instead of the txt and see what happens.

**Comment by radonthetyrant** [comment]
if you can do color with either escaped unicode characters or some kind of tags similar to [color=red]*[/color] then it's already possible. otherwise I might explore a proper way when adding embed messages

**Comment by samwiseg00** [comment]
i tried it and it did not work... not sure if its my syntax or something else. You need to tell it its json in the post header. I am not sure if its doing that.

**Comment by radonthetyrant** [comment]
ok thanks for checking it out, I'll update this issue when I have it implemented

**Comment by radonthetyrant** [comment]
![image](https://user-images.githubusercontent.com/4189978/38364642-c867c04a-38d9-11e8-8cf8-fad3842bc85f.png)

done

**Comment by samwiseg00** [comment]
Sweet! I will pull the changes and let you know!

**Comment by radonthetyrant** [comment]
Changed it up a bit, embed now looks sleeker (some uninteresting fields removed) and the torrent-passkey isnt visible anymore

![image](https://user-images.githubusercontent.com/4189978/38568763-c2880892-3ce9-11e8-8dea-a407ca4875e9.png)

**Comment by samwiseg00** [comment]
Sweet! I will update it. Thanks!
