### ISSUE TITLE
Webhook fails when there is no label

### ISSUE THREAD

**Issue by mikeluyten** [radonthetyrant/rutorrent-discord#4]
When there is no label on the torrent, sends the following in the request `{"name":"Label","value":""}` which fails when it gets to discord.

Maybe set the value be set to `null` unless being overwritten?

**Comment by radonthetyrant** [comment]
Hello,
Thanks for the report!
Should be fixed in fc951e7ff810a0c1cc35fbfa76043ea32b48b1ee
Please update to the latest version.

**Comment by radonthetyrant** [comment]
Closing this. if the issue persists, reopen
