### ISSUE TITLE
Not seeing any notification

### ISSUE THREAD

**Issue by tssgery** [radonthetyrant/rutorrent-discord#6]
I've installed the discordpush plugin but am not receiving any notifications. Is there a way to debug what is happening?

rutorrent is in ~/.www/rutorrent
discordpush contents in ~/www/rutorrent/plugins/discordpush
rutorrent sees the plugin and allows me to configure it
discord.dat is at .www/rutorrent/share/users/helsing/settings/discord.dat

webook url was tested with curl and is valid

**Comment by radonthetyrant** [comment]
you could check the logfiles for php or your webserver. I suspect there may be a php extension missing or some kind of misconfiguration?

Which php version are you using?

**Comment by tssgery** [comment]
It's php 7.0 but I don't have access to the webserver logs. I'll try to get them from my provider.
